services:
  angular:
    image: node:24-alpine
    container_name: angular-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "4200:4200"
    command: sh -c "npm install && npm run start -- --host 0.0.0.0 --port 4200 --poll=2000"